name: conjure-up
version: 2.6.9
version-script: |
  echo "$SNAPCRAFT_PROJECT_VERSION-$(date +%Y%m%d.%H%m)"
summary: Package runtime for conjure-up spells
description: >
  This package provides conjure-up, an interface to installing spells that provide
  the user with an end to end walkthrough experience for installing and using big
  software.
confinement: classic
grade: stable
base: core18
apps:
  conjure-up:
    command: bin/wrappers/conjure-up
  conjure-down:
    command: bin/wrappers/conjure-down
  juju:
    command: bin/wrappers/juju
  juju-wait:
    command: bin/wrappers/juju-wait
parts:
  conjure-up:
    source: .
    plugin: python
    requirements:
    - requirements.txt
    stage:
    - -README.md
    - -usr/share/*python*
    stage-packages:
    - bsdtar
    - jq
    - pwgen
    - libsodium23
    build-packages:
    - lsb-release
    stage-snaps:
    - juju
  spells:
    source: https://github.com/conjure-up/spells.git
    source-type: git
    plugin: dump
    organize:
      '*': spells/
    stage:
    - -README.md
    after:
    - conjure-up
  wrappers:
    source: wrappers
    plugin: dump
    organize:
      '*': bin/wrappers/
